spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.126/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
      default-property-inclusion: non_null #这个注释表示如果字段是null，就不返回给前端
server:
  context-path: /sell